batch_size: 1
body_pose_prior_weights:
- 404.0
- 404.0
- 57.4
- 4.78
body_prior_type: l2
body_tri_idxs:
- - 5
  - 12
- - 2
  - 9
camera_type: persp
coll_loss_weights:
- 0.0
- 0.0
- 0.01
- 1.0
config: cfg_files/fit_smpl.yaml
data_folder: ./testing_data/image_data/rp_dennis_posed_004
data_weights:
- 1.0
- 1.0
- 1.0
- 1.0
dataset: openpose
degrees:
- 0
- 90
- 180
- 270
depth_loss_weight: 100.0
df_cone_height: 0.0001
expr_weights:
- 100.0
- 50.0
- 10.0
- 5.0
face_joints_weights:
- 0.0
- 0.0
- 0.0
- 2.0
flat_hand_mean: false
float_dtype: float32
focal_length: 5000.0
ftol: 1.0e-09
gender: neutral
gender_lbl_type: none
gtol: 1.0e-09
hand_joints_weights:
- 0.0
- 0.0
- 0.0
- 2.0
hand_pose_prior_weights:
- 100.0
- 50.0
- 10.0
- 5.0
ign_part_pairs:
- 9,16
- 9,17
- 6,16
- 6,17
- 1,2
- 12,22
img_folder: color
init_joints_idxs:
- 9
- 12
- 2
- 5
interactive: true
interpenetration: false
jaw_pose_prior_weights: null
jaw_prior_type: l2
joints_to_ign:
- 1
- 9
- 12
keyp_folder: keypoints
left_hand_prior_type: l2
loss_type: smplify
lr: 1.0
max_collisions: 128
max_persons: 1
maxiters: 30
mesh_folder: meshes
model_folder: ./smplx/models
model_type: smpl
num_gaussians: 8
num_pca_comps: 12
optim_expression: true
optim_hands: true
optim_jaw: true
optim_shape: true
optim_type: lbfgsls
part_segm_fn: ''
penalize_outside: true
point2plane: false
prior_folder: priors
result_folder: results
rho: 100.0
right_hand_prior_type: l2
save_meshes: true
shape_weights:
- 100.0
- 50.0
- 10.0
- 5.0
side_view_thsh: 25
summary_folder: summaries
use_cuda: true
use_face: false
use_face_contour: false
use_hands: false
use_joints_conf: true
use_pca: true
use_vposer: true
visualize: false
vposer_ckpt: ./vposer/models
